name: Backend CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t brayanbj27/bd-create-gym-services .
      - name: Publish image to docker hub
        run: docker push brayanbj27/bd-create-gym-services:latest   

  deploy: 
    needs: build
    runs-on: bj-add    
    steps:
      - name: Pull image from docker hub
        run: docker pull brayanbj27/bd-create-gym-services:latest
      - name: Delete Old Container
        run: docker rm -f gymAddService || true
      - name: Run docker container
        run: docker run -d --name gymAddService --network gym_network -p 8088:8088 brayanbj27/bd-create-gym-services